
CC     := g++
CFLAGS := -Wall -Wextra

pointers-and-references : pointers-and-references.cpp
	$(CC) $(CFLAGS) -std=c++11 $<

function-overloading : function-overloading.cpp
	$(CC) $(CFLAGS) $<

polymorphism : polymorphism.cpp
	$(CC) $(CFLAGS) $<

clean :
	rm -f a.out
